#!/bin/bash

$BIN/select ROOT/P/N down  # nothing
$BIN/select ROOT/P/N up    # nothing

$BIN/select ROOT/P/N left
$BIN/select ROOT/P/N up
$BIN/select ROOT/P/N up    # nothing

$BIN/select ROOT/P/N left
$BIN/select ROOT/P/N up
$BIN/select ROOT/P/N right
$BIN/select ROOT/P/N right
$BIN/select ROOT/P/N down

$BIN/select ROOT/P/N up
$BIN/select ROOT/P/N left
$BIN/select ROOT/P/N left
$BIN/select ROOT/P/N down
$BIN/select ROOT/P/N right
$BIN/select ROOT/P/N down
$BIN/select ROOT/P/N right
