#!/bin/bash

$BIN/pipe ROOT/P/N
echo "jq '. * 2'" | $BIN/cat ROOT/P/N

$BIN/select ROOT/P/N left
$BIN/pipe ROOT/P/N
echo "jq '. + 2'" | $BIN/cat ROOT/P/N

$BIN/insert ROOT/P
$BIN/pipe ROOT/P/N
echo sed s/world/again/ | $BIN/cat ROOT/P/N

$BIN/select ROOT/P/N left
$BIN/pipe ROOT/P/N
echo wc -c | $BIN/cat ROOT/P/N

$BIN/pipe ROOT/P/N
echo "jq '. * 2'" | $BIN/cat ROOT/P/N
