#!/bin/bash

$BIN/pipe P
echo "jq '. * 2'" | $BIN/cat P

$BIN/select P left
$BIN/pipe P
echo "jq '. + 2'" | $BIN/cat P

$BIN/insert P
$BIN/pipe P
echo sed s/world/again/ | $BIN/cat P

$BIN/select P left
$BIN/pipe P
echo wc -c | $BIN/cat P
$BIN/pipe P
echo "jq '. * 2'" | $BIN/cat P
