#!/bin/bash

$BIN/clone ROOT/P/N
echo "jq '. + 2'" | $BIN/cat ROOT/P/N

$BIN/select ROOT/P/N left
$BIN/clone ROOT/P/N
echo "wc -l" | $BIN/cat ROOT/P/N

$BIN/select ROOT/P/N left
$BIN/clone ROOT/P/N
echo "ls -l" | $BIN/cat ROOT/P/N
