#!/bin/bash

$BIN/new ROOT

$BIN/insert ROOT/P
$BIN/select ROOT/P/N left    # nowhere to go
$BIN/select ROOT/P/N right   # nowhere to go

$BIN/pipe ROOT/P/N
$BIN/select ROOT/P/N right   # nowhere to go
$BIN/select ROOT/P/N left
$BIN/select ROOT/P/N right

echo wc | $BIN/cat ROOT/P/N
echo wc -l | $BIN/cat ROOT/P/N

$BIN/select ROOT/P/N left
echo ls -l | $BIN/cat ROOT/P/N

$BIN/select ROOT/P/N right
open -g http://localhost:8000
