#!/bin/bash

cd $TMPDIR
mkdir P
touch P/stream

sh -c "$BIN/serve P &"
open -g http://localhost:8000
sleep 1

$BIN/insert P
$BIN/select P left    # nowhere to go
$BIN/select P right   # nowhere to go

$PAUSE
$BIN/pipe P
$BIN/select P right   # nowhere to go
$PAUSE
$BIN/select P left
$PAUSE
$BIN/select P right

$PAUSE
echo wc | $BIN/cat P
$PAUSE
echo wc -l | $BIN/cat P

$PAUSE
$BIN/select P left
echo ls -l | $BIN/cat P

$PAUSE
$BIN/select P right

open -g http://localhost:8000
sleep 1
