#!/bin/bash

cd $TMPDIR
mkdir P

sh -c "$BIN/serve P &"
sleep 0.5
open -g http://localhost:8000

# make a root node
ID=$($BIN/i P)
mkdir -p P/node/$ID
echo echo Hello, world. > P/node/$ID/run
chmod +x P/node/$ID/run
ln -s /dev/null P/node/$ID/stdin
$BIN/run P $ID

# pipe to a new node
$PAUSE
PARENT=$ID
ID=$($BIN/i P)
mkdir -p P/node/$ID
echo cat > P/node/$ID/run
chmod +x P/node/$ID/run
ln -s ../$PARENT/stdout P/node/$ID/stdin
$BIN/run P $ID

find -L . -samefile P/node/$PARENT/stdout -name "*stdin" | \
  xargs dirname | \
  xargs basename | \
  jq --argjson parent "$PARENT" -s -c '
    {"tree": {($parent | tostring): {"$set": map(tostring)}}}' >> P/stream

$BIN/watch P $ID &
$PAUSE
echo wc > P/node/$ID/run
$PAUSE
echo wc -l > P/node/$ID/run
kill %%

$BIN/watch P $PARENT &
$PAUSE
echo ls -l > P/node/$PARENT/run

sleep 100
echo finished
